### ISSUE TITLE
修改用户信息必须修改手机号

### ISSUE THREAD

**Issue by Mrzhuhanxin** [febsteam/FEBS-Shiro#185]
### 问题描述
修改用户任意信息必须修改手机号，原因是脱敏处理之后传给前端，修改用户信息的时候不应该进行脱敏处理，所以不应该在实体类上加脱敏处理
### 复现步骤
只修改用户状态，提交修改的时候提示请填写正确的手机号
### 相关截图

![20200630102231](https://user-images.githubusercontent.com/43130589/86076584-e82b6f00-babc-11ea-9fb9-b443df47da22.png)

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
只是为了演示数据脱敏使用方式，可以去掉。

**Comment by wuyouzhuguli** [comment]
数据脱敏一般是在展示数据的时候使用，展示的数据不涉及修改。

**Comment by Mrzhuhanxin** [comment]
列表展示的时候可以做脱敏处理，但是这个是修改用户信息的界面，也就是说，不管修改任何信息，都需要附带修改手机号

**Comment by freiday** [comment]
怎么配置后天菜单

**Comment by wuyouzhuguli** [comment]
@Mrzhuhanxin 展示的数据和修改页面的数据可以用两个model装载

**Comment by Mrzhuhanxin** [comment]
@wuyouzhuguli 明白，我自己这边改好了，跟你说一下

**Comment by mgzu** [comment]
@wuyouzhuguli 数据脱敏可以设置几个级别，requestmapping 可以禁用或启用某个级别（大于或等于当前级别的数据会被处理），这样会不会更灵活些

**Comment by wuyouzhuguli** [comment]
@mgzu 嗯嗯，马大老思路不错。
