### ISSUE TITLE
请问演示页面的版本

### ISSUE THREAD

**Issue by MrXiaoguai** [febsteam/FEBS-Shiro#186]
### 问题描述
近期在开发资源权限相关内容，在本地部署时发现和演示页面的效果差很多，主要是系统管理下的角色管理和菜单管理页面，想问下演示页面的版本，感激不尽。

### 复现步骤
简单描述下问题复现的步骤

### 相关截图
提供相关截图，以协助问题分析

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
演示环境和代码是同步的。效果差很多？上个图看看吧。

**Comment by MrXiaoguai** [comment]
![image](https://user-images.githubusercontent.com/22787550/87115816-df018580-c2a6-11ea-9892-cf09c1b4d122.png)
上图是本地部署时的角色管理页面。
![image](https://user-images.githubusercontent.com/22787550/87116095-88487b80-c2a7-11ea-9e6f-940d4c5cbc63.png)
上图是在线演示的角色管理页面。

**Comment by wuyouzhuguli** [comment]
你下载的是1.0的，master分支（v2.0）才是最新代码。
