### ISSUE TITLE
多选项卡模式下id污染问题

### ISSUE THREAD

**Issue by wsuu** [febsteam/FEBS-Shiro#192]
多选项卡模式下，多个tab里的内容互相影响，污染严重，除了每个页面的各种id命名保持不一样（有点不现实），有没有什么好的方法可以解决？
打开或切换tab时，将前一个tab的dom移除并保存在零时文件中，切换到该tab时再读取添加dom的思路不知道可行不

**Comment by wuyouzhuguli** [comment]
简单的问题不要复杂化。取dom都用$view.find('xxxx')获取，$view就是当前页面的根dom，这个ID保持唯一。

**Comment by wsuu** [comment]
不是取dom的问题，比如页面重写了某些样式呢，以及相同定义的同名template。
比如在某页面重新了单元格高度
<style type="text/css">
    .layui-table-cell{ height: auto;}
</style>
打开其他页面也受这个样式影响了。
以及某页面定义了template
<script type="text/html" id="xxx">
其他页面也定义了相同的template也会互相受影响。

**Comment by wuyouzhuguli** [comment]
css也是一样的，比如当前页面的根dom ID为root-demo，那么css编写，前面都需要加#root-demo；

template指定不同的id。

如果你觉得每个页面用唯一id区分很麻烦，你可以自己考虑更简单的实现方式，对于我个人来说，约定大于配置。

**Comment by wsuu** [comment]
嗯，谢谢。很多页面要用相同的数据库modle，所以template分别指定不同的id，可读性不够好，且页面一多起来控制唯一性也比较麻烦。

**Comment by wsuu** [comment]
如果在使用template的地方能加根dom前缀的方式使用就好了

**Comment by wuyouzhuguli** [comment]
基于iframe多标签页的框架可能会更适合你🤔

**Comment by wsuu** [comment]
每个页面定义template时都加上 跟dom id吧，只能这样了
