### ISSUE TITLE
刷新页面后有时会跳到首页

### ISSUE THREAD

**Issue by sysoncloud** [febsteam/FEBS-Shiro#193]
### 问题描述
简单描述下遇到的问题
单选项卡模式下, 进入用户管理 (部门/菜单管理...同),  按F5多次刷新页面(刷新次数三五次, 十次不定),  或地址栏回车,  经常会跳到首页. 不是刷新后只会在当前页面吗

### 复现步骤
简单描述下问题复现的步骤

### 相关截图
![febs-1](https://user-images.githubusercontent.com/8220242/88898575-80b13c80-d27f-11ea-9245-c8420f242e5b.png)

> issue模板，by MrBird.

**Comment by mgzu** [comment]
@sysoncloud 已经提 pr 了

**Comment by wsuu** [comment]
点击 表单提交按钮 上传 按钮会大概率 触发当前页面刷新，一并修复了吗？

**Comment by mgzu** [comment]
> 点击 表单提交按钮 上传 按钮会大概率 触发当前页面刷新，一并修复了吗？

如果存在，可以提一个新的 issue，这个 issue 跟你说的问题根源不同
