### ISSUE TITLE
登陆页面多刷新几次后台报IO异常

### ISSUE THREAD

**Issue by DongsGit** [febsteam/FEBS-Shiro#195]
### 问题描述
登陆页面多刷新几次后台报错IOException:你的主机中的软件中止了一个已建立的连接

### 复现步骤
打开登陆页面按f5多快速多刷新几次
### 相关截图
![OZ7KLZ 0N42FEZO Q4 CL3R](https://user-images.githubusercontent.com/36791760/89093266-57adba80-d3eb-11ea-8c1b-c6083fc6d615.png)

@notlcry @pangPython @gelibo @wuyouzhuguli

**Comment by Sweety-Feel** [comment]
我也是遇到这个问题，在项目启动完毕后，打开浏览器到登录页面后，直接关闭，后台就会报断开连接

**Comment by DongsGit** [comment]
> 我也是遇到这个问题，在项目启动完毕后，打开浏览器到登录页面后，直接关闭，后台就会报断开连接

应该是验证码生成插件的问题，写的太慢了以至于页面来不及响应

**Comment by wuyouzhuguli** [comment]
验证码已做限流处理。
