### ISSUE TITLE
发现一个严重的BUG:编辑在线用户的权限保存后,不能正确生效

### ISSUE THREAD

**Issue by dsadsaad** [febsteam/FEBS-Shiro#197]
### 问题描述
使用管理员账号操作禁止一名在线用户的权限后,该权限对应的接口仍然能获取数据.
需要管理员踢出该用户,获取该用户自行重新登录权限才能正确生效.经过PostMan接口测试能稳定重现.

**Comment by wuyouzhuguli** [comment]
用户权限是登录时存在内存的，生命周期和session一致。超级管理员修改别人的权限并不影响别人已登录那部分。要么选择用户每次操作都重新获取权限，要么选择目前的模式。个人更侧重后者，因为用户的权限一般随着账号的创建后就固定了。或者您可以自己实现登录用户权限修改后强制登出操作。

**Comment by dsadsaad** [comment]
> 用户权限是登录时存在内存的，生命周期和session一致。超级管理员修改别人的权限并不影响别人已登录那部分。要么选择用户每次操作都重新获取权限，要么选择目前的模式。个人更侧重后者，因为用户的权限一般随着账号的创建后就固定了。或者您可以自己实现登录用户权限修改后强制登出操作。

感谢回复.
是的,这个确实是shiro的锅,,没办法在session保持连接的情况下刷新该用户的权限信息.

**Comment by dsadsaad** [comment]
> 用户权限是登录时存在内存的，生命周期和session一致。超级管理员修改别人的权限并不影响别人已登录那部分。要么选择用户每次操作都重新获取权限，要么选择目前的模式。个人更侧重后者，因为用户的权限一般随着账号的创建后就固定了。或者您可以自己实现登录用户权限修改后强制登出操作。

在这感谢一下作者,FEBS给了我一个参考的样板,我是仿造FEBS写一个动态权限控制的分布式权限校验微服务.

**Comment by printlin** [comment]
嗨，我也遇到了同样的问题，可以尝试修改clearCache方法解决。
在文件：common/authentication/ShiroRealm.java
`    public void clearCache() {
        Collection<Session> sessions = sessionDAO.getActiveSessions();
        for (Session session : sessions) {
            if (session.getAttribute(DefaultSubjectContext.PRINCIPALS_SESSION_KEY) == null) {
                continue;
            }
            SimplePrincipalCollection principalCollection = (SimplePrincipalCollection) session
                    .getAttribute(DefaultSubjectContext.PRINCIPALS_SESSION_KEY);
            super.clearCache(principalCollection);
        }
//        PrincipalCollection principals = SecurityUtils.getSubject().getPrincipals();
//        super.clearCache(principals);
    }`
