### ISSUE TITLE
菜单管理如何同步

### ISSUE THREAD

**Issue by Hurry-LJ** [febsteam/FEBS-Shiro#198]
### 问题描述
刷新尝试过，重新运行过，数据库有显示添加

### 复现步骤
简单描述下问题复现的步骤

### 相关截图
![image](https://user-images.githubusercontent.com/67175621/91944063-12edaa00-ed30-11ea-90f2-53ae713eddca.png)

> issue模板，by MrBird.

**Comment by mgzu** [comment]
能描述清楚些么

**Comment by wuyouzhuguli** [comment]
估计说的是新增了菜单左侧没显示吧，请对当前用户角色授权。

**Comment by Hurry-LJ** [comment]
> 估计说的是新增了菜单左侧没显示吧，请对当前用户角色授权。

我用的全权限的MrBird，是左边菜单新增没显示，但是修改原本的名字可以

**Comment by Hurry-LJ** [comment]
> 能描述清楚些么 @Hurry-LJ

![image](https://user-images.githubusercontent.com/67175621/91977894-e5b3f280-ed55-11ea-9ddb-8bee73df7807.png)
左侧黑色的菜单没有更新

**Comment by Hurry-LJ** [comment]
> 估计说的是新增了菜单左侧没显示吧，请对当前用户角色授权。

明白了，是要授权，在新增角色为刚刚建的加权限，谢谢各位大佬，感谢
