### ISSUE TITLE
今日更新代码后febs.shiro.success_url配置无效

### ISSUE THREAD

**Issue by wsuu** [febsteam/FEBS-Shiro#201]
### 问题描述
今日更新代码后febs.shiro.success_url配置无效，仍旧跳转到默认首页

### 复现步骤
febs.shiro.success_url配置登陆后的页面，更新后跳转到了默认首页

**Comment by wuyouzhuguli** [comment]
登录成功跳转首页目前实际是在login.html的138行代码控制
```
location.href = ctx + 'index';
```

**Comment by wsuu** [comment]
好吧，貌似config.js里也有相关配置，建议配置统一下

**Comment by wsuu** [comment]
> 登录成功跳转首页目前实际是在login.html的138行代码控制
> 
> ```
> location.href = ctx + 'index';
> ```

改了这里会同时仍旧打开了默认首页，2个tab，应该是这里不改，改config.js 里的 entry

**Comment by wsuu** [comment]
改config.js 里的 entry，又会出现新问题，清理浏览器，部署后首次登录，切换账号 等操作，大概率会出现 两个同名tab，tab主体div隐藏的

**Comment by wsuu** [comment]
![image](https://user-images.githubusercontent.com/7030106/92266967-b1396580-ef12-11ea-86c7-fbac85bed4c2.png)

**Comment by wsuu** [comment]
![image](https://user-images.githubusercontent.com/7030106/92324221-50c13a00-f072-11ea-9a05-4daf8d211188.png)
调试发现是此行执行两次导致

**Comment by wsuu** [comment]
$(window).on('hashchange', 
self.initPage = 
看代码，应该是这两个函数异步同时调用view.renderTabs导致tab.change里面判断var existsTab = tab.has(fileurl); 都为false导致。
因问题不是每次必现，目前未确定，只是推测。

**Comment by wsuu** [comment]
@wuyouzhuguli

**Comment by wsuu** [comment]
更新了代码，登陆后两个同名tab问题依旧存在 @wuyouzhuguli

**Comment by wuyouzhuguli** [comment]
![wuTiJx.gif](https://s1.ax1x.com/2020/09/07/wuTiJx.gif)
