### ISSUE TITLE
同时启用两个不同端口，会串session有什么好办法吗

### ISSUE THREAD

**Issue by wsuu** [febsteam/FEBS-Shiro#222]
同时启用两个不同端口，会串session有什么好办法吗

**Comment by xzf520** [comment]
复制一份一样的项目，将shiro配置文件中的cookie名称设置为不相同

**Comment by wsuu** [comment]
> 复制一份一样的项目，将shiro配置文件中的cookie名称设置为不相同
配置文件加了，并没有什么卵用。
server:
  servlet:
    session:
      cookie:
        name: xxxx

**Comment by wsuu** [comment]
正解是ShiroConfig.java
 sessionManager.getSessionIdCookie().setName("xxxx");

**Comment by xzf520** [comment]
正解
