### ISSUE TITLE
第一次登录选择记得等登录，重启服务后再次运行还是提示需要登录并没有记住并将有报错信息

### ISSUE THREAD

**Issue by kenx-max** [febsteam/FEBS-Shiro#224]
### 问题描述
第一次登录选择记得等登录，重启服务后再次运行还是提示需要登录并没有记住并再次登录有报错信息

### 相关截图
![image](https://user-images.githubusercontent.com/45358764/109113476-49ecc780-7777-11eb-909f-0b178b5ac33d.png)

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
已修复
