### ISSUE TITLE
form.on id冲突问题怎么解决比较好？

### ISSUE THREAD

**Issue by wsuu** [febsteam/FEBS-Shiro#225]
form.on('switch(status)', function (data)……
因为是多tab页面，所以相同name或者相同lay-filter在不同的tab里再所难免。
是否能通过tab的div id来过滤一下，试了下，这里貌似不支持过滤选择。

**Comment by wuyouzhuguli** [comment]
#226 #225 两个issue其实是一个问题。系统多tab不是基于iframe的，多个tab页面html渲染后并不会移除，只是隐藏了非当前tab页，所以如果多个tab页面存在lay-filter相同或者id、class相同的情况，就会造成冲突。

建议每个页面最外层div取个唯一id，然后里面所有dom元素获取都在当前div内find，这样就不会冲突；lay-filter的值前面也加个类似的限定，比如xxx-status...
