### ISSUE TITLE
代码生成未发现前台代码

### ISSUE THREAD

**Issue by zilongzixue** [febsteam/FEBS-Shiro#228]
代码生成未发现前台代码

**Comment by jht385** [comment]
原版是不带的，想要可以用 https://github.com/jht385/FEBS-Shiro-jht

**Comment by jht385** [comment]
> 代码生成未发现前台代码



> 代码生成未发现前台代码

原版是不带的，想要带前端的可以用 https://github.com/jht385/FEBS-Shiro-jht

**Comment by wuyouzhuguli** [comment]
军舰你来啦

**Comment by jht385** [comment]
> 军舰你来啦

干湿你！T我出来，还不拉人家回去，你坏坏！我生气了，哄不好的那种，哼！

**Comment by wuyouzhuguli** [comment]
...

**Comment by zilongzixue** [comment]
> 
> 
> > 代码生成未发现前台代码
> 
> 原版是不带的，想要带前端的可以用 https://github.com/jht385/FEBS-Shiro-jht
好的，谢谢
