### ISSUE TITLE
配置server.servlet.context-path后调整完所有静态文件引用，eleTree组件样式丢失。

### ISSUE THREAD

**Issue by JiangZongshi** [febsteam/FEBS-Shiro#230]
### 问题描述
配置server.servlet.context-path后调整完所有静态文件引用，eleTree组件样式丢失。

### 复现步骤
1、application.yml 配置server.servlet.context-path
2、调整index.html及login.html 静态文件路径动态获取
3、所有控件均正常，但eleTree组件样式丢失
### 相关截图
调整后样式：
![image](https://user-images.githubusercontent.com/11846840/113234749-70e96c80-92d4-11eb-91e0-f6b3cfb4ce70.png)
调整前样式：
![image](https://user-images.githubusercontent.com/11846840/113234771-7b0b6b00-92d4-11eb-9803-9b24b97591d1.png)
> issue模板，by MrBird.

**Comment by JiangZongshi** [comment]
调整前：
![image](https://user-images.githubusercontent.com/11846840/113234993-ec4b1e00-92d4-11eb-9d4b-0cb2fae191df.png)
调整后：
![image](https://user-images.githubusercontent.com/11846840/113235017-f66d1c80-92d4-11eb-8e47-aae6cd090370.png)

**Comment by JiangZongshi** [comment]
目前是外层单独引用了eleTree.css文件解决的。

**Comment by alphye** [comment]
将所有使用@mvcResourceUrlProvider.getForLookupPath 来获取资源路径的地方，外边再套一层 @{}，如以下格式：

<link rel="stylesheet" th:href="@{${@mvcResourceUrlProvider.getForLookupPath('/layui/css/layui.css')}}" media="all">
<script th:src="@{${@mvcResourceUrlProvider.getForLookupPath('/layui/layui.js')}}"></script>

亲测有效
