### ISSUE TITLE
配置多数据源-oracle

### ISSUE THREAD

**Issue by shaowen** [febsteam/FEBS-Shiro#231]
### 问题描述
简单描述下遇到的问题
配置Oracle启动报错
![image](https://user-images.githubusercontent.com/5210084/113680360-56a7f800-96f3-11eb-963c-b1c6307c15f0.png)

### 复现步骤
简单描述下问题复现的步骤
本身架构模式连接的：mysql 两个库 现在我增加了了一个oracle连接 报上图错  如图1

 
![image](https://user-images.githubusercontent.com/5210084/113684894-434b5b80-96f8-11eb-9de7-d4c9de9912d9.png)

### 相关截图
提供相关截图，以协助问题分析

项目图片资料

maven 手动导入图片 
![image](https://user-images.githubusercontent.com/5210084/113683949-53af0680-96f7-11eb-9b3b-2ccba1834ba8.png)

oracle数据版本
![image](https://user-images.githubusercontent.com/5210084/113683988-60335f00-96f7-11eb-9af9-09311b1eee82.png)

maven生产目录
![image](https://user-images.githubusercontent.com/5210084/113684557-ee0f4a00-96f7-11eb-915e-d643c825fdbb.png)

idea连接数据库正常
![image](https://user-images.githubusercontent.com/5210084/113685140-8279ac80-96f8-11eb-9619-7f132a01df60.png)

> issue模板，by MrBird.

FEBS-Shiro 2.0

**Comment by wuyouzhuguli** [comment]
spring.dynamic.hikari.connection-test-query配置用于测试数据库连接可用性，MySQL的语句为select 1，Oracle的语句为select 1 from dual，所以报找不到FROM关键字异常，可以将这个配置去掉。

**Comment by shaowen** [comment]
你说的这个  oracle 测试语句   我已经注释了的  Oracle的语句为select 1 from dual，

**Comment by shaowen** [comment]
> spring.dynamic.hikari.connection-test-query配置为测试数据库连接可用，MySQL的语句为select 1，Oracle的语句为select 1从double，所以报发现FROM关键字异常，可以将这个配置去掉。

你说这个 oracle 测试语句， 我注释了的，

**Comment by wuyouzhuguli** [comment]
注释了就不会出现你说的异常，请核实
