### ISSUE TITLE
not adaptable with layui 2.6.7

### ISSUE THREAD

**Issue by fanzhouworld** [febsteam/FEBS-Shiro#234]
### 问题描述
把 layui 升级到 2.6.7 时，view.js 报错 layui error hint: dropdown Module already exists。影响 tab 最右边的 x 按钮，和 form 的 action-more。
因为 layui 从 2.6.0 添加了 dropdown 模块，与 febs/lay/dropdown.js 的模块冲突。尝试过改后者模块的名字，无法解决，请求帮助。

### 复现步骤
把 layui 升级到 2.6.7，打开任意一个用到 view.js 的 form 页面。

### 相关截图
很普遍，用到 view.js 的 form 页面都会有这个问题。

> issue模板，by MrBird.

**Comment by fanzhouworld** [comment]
已解决，除 layui 外，修改所有 dropdown 字眼。即同时修改 view.js 和 dropdown.js 里面有关 dropdown 的字眼为另一变量名，相应 html use 语句也做相应修改，febs.css 也做变量名修改，避免影响 layui 自带的 dropdown 的 style。

**Comment by wuyouzhuguli** [comment]
感谢反馈
